In [1]:
import numpy as np

In [12]:
suger_range = np.random.randint(11)
print(suger_range)

7


In [13]:
arr = np.random.randint(suger_range , size=(16,21))
print(arr)

[[2 0 6 2 3 4 3 6 5 0 4 5 4 0 2 1 4 6 2 6 0]
 [2 4 6 4 4 3 0 1 0 4 5 1 3 6 4 5 1 2 6 3 4]
 [0 3 1 6 2 4 4 6 0 3 2 6 0 3 3 4 3 3 4 3 4]
 [0 4 0 5 4 5 1 5 1 3 6 3 4 6 1 0 5 1 0 5 1]
 [1 6 1 6 6 1 6 5 6 2 3 6 4 0 3 6 4 0 4 5 6]
 [3 1 0 5 1 5 4 3 4 0 4 1 4 3 1 2 1 0 2 4 3]
 [3 3 4 2 2 6 4 0 6 3 2 6 5 5 0 2 3 1 2 0 2]
 [0 3 3 0 4 4 1 2 1 3 1 6 6 0 1 6 0 5 0 4 5]
 [6 2 5 2 4 2 4 4 6 0 1 2 3 0 6 0 5 1 1 5 2]
 [2 1 4 5 6 1 0 5 1 4 1 0 0 0 4 5 3 1 4 5 2]
 [4 2 4 0 2 1 5 2 1 0 2 3 6 0 1 6 0 4 2 2 6]
 [1 4 3 3 0 1 4 6 6 6 0 3 0 0 6 5 6 0 1 2 5]
 [5 3 1 0 2 5 6 6 4 3 6 4 2 2 5 0 3 0 0 3 0]
 [0 0 2 3 0 2 3 2 6 3 2 0 4 0 3 5 3 2 0 4 2]
 [3 4 6 2 0 6 6 4 5 4 4 6 6 0 5 1 3 5 5 1 6]
 [2 2 3 4 1 0 6 1 2 3 4 2 5 5 4 0 2 4 2 0 1]]


In [4]:
def get_suger_avg(array):
    return np.round(np.average(array , axis=1), 3)

In [14]:
avgArrSuger = get_suger_avg(arr)
print(avgArrSuger)

[3.095 3.238 3.048 2.857 3.857 2.429 2.905 2.619 2.905 2.571 2.524 2.952
 2.857 2.19  3.905 2.524]


In [7]:
patients_avg_time = np.random.exponential(size=16)

In [6]:
def max_suger_day(array):
    return np.argmax(np.average(array , axis=0)) + 1

In [8]:
def max_suger_day(array):
    return np.argmax(np.average(array , axis=0)) + 1

In [9]:
def max_suger_patient(array):
    return np.argmax(get_suger_avg(array)) + 1

In [10]:
def get_max_time_patient(array):
    return np.argmax(array) + 1

In [11]:
print('The day with the maximum suger is: ', 'day ',max_suger_day(arr)) 
print('The patient with maximum avg suger is: ', 'patient number',max_suger_patient(arr)) 
print('The patient who waited the most is: ', 'patient number',get_max_time_patient(patients_avg_time))

The day with the maximum suger is:  day  4
The patient with maximum avg suger is:  patient number 7
The patient who waited the most is:  patient number 4
